name: Build Executables and Release

on:
  push:
    tags:
      - 'v*'  

permissions:
  contents: write  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Tkinter (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk tk

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Compile with PyInstaller
      run: |
        pyinstaller main.spec

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable-${{ matrix.os }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Ubuntu artifact
      uses: actions/download-artifact@v4
      with:
        name: executable-ubuntu-latest
        path: artifacts/ubuntu-latest

    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: executable-windows-latest
        path: artifacts/windows-latest

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }} 
        name: Release ${{ github.ref_name }}
        body: "Automated release for ${{ github.ref_name }}"
        draft: false
        prerelease: false
        files: |
          artifacts/ubuntu-latest/dist/main
          artifacts/windows-latest/dist/main.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}